# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: West London Coders
email: steve.v.brewer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn, discuss and practice code locally
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://westlondoncoders.com" # the base hostname & protocol for your site
twitter_username: svpersteve
github_username:  svpersteve

# Build settings
markdown: kramdown
